var annotated_dup =
[
    [ "BalisongEngine", null, [
      [ "BalisongEngineAllocator", null, [
        [ "Allocator", "class_balisong_engine_1_1_balisong_engine_allocator_1_1_allocator.html", null ],
        [ "BaseResource", "class_balisong_engine_1_1_balisong_engine_allocator_1_1_base_resource.html", "class_balisong_engine_1_1_balisong_engine_allocator_1_1_base_resource" ],
        [ "Chunk", "struct_balisong_engine_1_1_balisong_engine_allocator_1_1_chunk.html", "struct_balisong_engine_1_1_balisong_engine_allocator_1_1_chunk" ],
        [ "PoolAllocator", "class_balisong_engine_1_1_balisong_engine_allocator_1_1_pool_allocator.html", "class_balisong_engine_1_1_balisong_engine_allocator_1_1_pool_allocator" ]
      ] ],
      [ "BalisongEngineComponents", null, [
        [ "Anim", "struct_balisong_engine_1_1_balisong_engine_components_1_1_anim.html", "struct_balisong_engine_1_1_balisong_engine_components_1_1_anim" ],
        [ "AnimatorComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_animator_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_animator_component" ],
        [ "AudioSourceComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_audio_source_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_audio_source_component" ],
        [ "BarComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_bar_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_bar_component" ],
        [ "BaseComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_base_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_base_component" ],
        [ "BoxColliderComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_box_collider_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_box_collider_component" ],
        [ "ButtonComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_button_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_button_component" ],
        [ "CameraBorderComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_camera_border_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_camera_border_component" ],
        [ "CircleColliderComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_circle_collider_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_circle_collider_component" ],
        [ "ColliderComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_collider_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_collider_component" ],
        [ "DeflectComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_deflect_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_deflect_component" ],
        [ "DelayedDestroyComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_delayed_destroy_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_delayed_destroy_component" ],
        [ "DestroyOnCollideComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_destroy_on_collide_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_destroy_on_collide_component" ],
        [ "EnemySpawnerComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_enemy_spawner_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_enemy_spawner_component" ],
        [ "FollowCameraComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_follow_camera_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_follow_camera_component" ],
        [ "FollowMouseComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_follow_mouse_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_follow_mouse_component" ],
        [ "FooComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_foo_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_foo_component" ],
        [ "MoveAnimComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_move_anim_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_move_anim_component" ],
        [ "MoveComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_move_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_move_component" ],
        [ "PlayerMoveComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_player_move_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_player_move_component" ],
        [ "PursuitComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_pursuit_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_pursuit_component" ],
        [ "QuadRenderComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_quad_render_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_quad_render_component" ],
        [ "RandomTransformComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_random_transform_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_random_transform_component" ],
        [ "RotateComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_rotate_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_rotate_component" ],
        [ "ScrollerComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_scroller_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_scroller_component" ],
        [ "ShootComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_shoot_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_shoot_component" ],
        [ "SimpleShootComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_simple_shoot_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_simple_shoot_component" ],
        [ "SineTransformComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_sine_transform_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_sine_transform_component" ],
        [ "SpawnOnCollideComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_spawn_on_collide_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_spawn_on_collide_component" ],
        [ "SpawnOnDestroyComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_spawn_on_destroy_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_spawn_on_destroy_component" ],
        [ "SpinComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_spin_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_spin_component" ],
        [ "SpriteRendererComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_sprite_renderer_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_sprite_renderer_component" ],
        [ "TimerComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_timer_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_timer_component" ],
        [ "TransformComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_transform_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_transform_component" ],
        [ "VelocityMeterComponent", "class_balisong_engine_1_1_balisong_engine_components_1_1_velocity_meter_component.html", "class_balisong_engine_1_1_balisong_engine_components_1_1_velocity_meter_component" ]
      ] ],
      [ "BalisongEngineFramework", null, [
        [ "ActionEvent", "class_balisong_engine_1_1_balisong_engine_framework_1_1_action_event.html", "class_balisong_engine_1_1_balisong_engine_framework_1_1_action_event" ],
        [ "Application", "class_balisong_engine_1_1_balisong_engine_framework_1_1_application.html", "class_balisong_engine_1_1_balisong_engine_framework_1_1_application" ],
        [ "AppWindow", "class_balisong_engine_1_1_balisong_engine_framework_1_1_app_window.html", "class_balisong_engine_1_1_balisong_engine_framework_1_1_app_window" ],
        [ "AppWindowData", "struct_balisong_engine_1_1_balisong_engine_framework_1_1_app_window_data.html", "struct_balisong_engine_1_1_balisong_engine_framework_1_1_app_window_data" ],
        [ "Audio", "struct_balisong_engine_1_1_balisong_engine_framework_1_1_audio.html", "struct_balisong_engine_1_1_balisong_engine_framework_1_1_audio" ],
        [ "AudioManager", "class_balisong_engine_1_1_balisong_engine_framework_1_1_audio_manager.html", null ],
        [ "Gizmos", "class_balisong_engine_1_1_balisong_engine_framework_1_1_gizmos.html", null ],
        [ "Input", "class_balisong_engine_1_1_balisong_engine_framework_1_1_input.html", null ],
        [ "Random", "class_balisong_engine_1_1_balisong_engine_framework_1_1_random.html", null ],
        [ "ResizeEventData", "struct_balisong_engine_1_1_balisong_engine_framework_1_1_resize_event_data.html", "struct_balisong_engine_1_1_balisong_engine_framework_1_1_resize_event_data" ],
        [ "TimeEngine", "class_balisong_engine_1_1_balisong_engine_framework_1_1_time_engine.html", "class_balisong_engine_1_1_balisong_engine_framework_1_1_time_engine" ]
      ] ],
      [ "BalisongEngineOCM", null, [
        [ "ColliderManager", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_collider_manager.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_collider_manager" ],
        [ "CreditsBackButtonPrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_credits_back_button_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_credits_back_button_prefab" ],
        [ "CreditsButtonPrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_credits_button_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_credits_button_prefab" ],
        [ "CreditsPrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_credits_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_credits_prefab" ],
        [ "EnemyBulletImpactPrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_enemy_bullet_impact_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_enemy_bullet_impact_prefab" ],
        [ "EnemyBulletPrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_enemy_bullet_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_enemy_bullet_prefab" ],
        [ "EnemyExplodePrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_enemy_explode_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_enemy_explode_prefab" ],
        [ "EnemyMuzzlePrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_enemy_muzzle_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_enemy_muzzle_prefab" ],
        [ "EnemyPrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_enemy_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_enemy_prefab" ],
        [ "EnemySpawnerPrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_enemy_spawner_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_enemy_spawner_prefab" ],
        [ "GameObject", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_game_object.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_game_object" ],
        [ "GameObjectCollection", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_game_object_collection.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_game_object_collection" ],
        [ "GameObjectRef", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_game_object_ref.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_game_object_ref" ],
        [ "GameObjectRefSet", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_game_object_ref_set.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_game_object_ref_set" ],
        [ "LoseUIPrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_lose_u_i_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_lose_u_i_prefab" ],
        [ "MenuButtonPrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_menu_button_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_menu_button_prefab" ],
        [ "MousePrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_mouse_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_mouse_prefab" ],
        [ "PlayButtonPrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_play_button_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_play_button_prefab" ],
        [ "PlayerExplodePrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_player_explode_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_player_explode_prefab" ],
        [ "PlayerPrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_player_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_player_prefab" ],
        [ "Prefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_prefab" ],
        [ "PrefabManager", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_prefab_manager.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_prefab_manager" ],
        [ "RetryButtonPrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_retry_button_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_retry_button_prefab" ],
        [ "SpawnCfg", "struct_balisong_engine_1_1_balisong_engine_o_c_m_1_1_spawn_cfg.html", "struct_balisong_engine_1_1_balisong_engine_o_c_m_1_1_spawn_cfg" ],
        [ "TitlePrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_title_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_title_prefab" ],
        [ "TutorialPrefab", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_tutorial_prefab.html", "class_balisong_engine_1_1_balisong_engine_o_c_m_1_1_tutorial_prefab" ]
      ] ],
      [ "BalisongEngineRenderer", null, [
        [ "Camera", "class_balisong_engine_1_1_balisong_engine_renderer_1_1_camera.html", "class_balisong_engine_1_1_balisong_engine_renderer_1_1_camera" ],
        [ "CameraConfig", "struct_balisong_engine_1_1_balisong_engine_renderer_1_1_camera_config.html", "struct_balisong_engine_1_1_balisong_engine_renderer_1_1_camera_config" ],
        [ "DrawCommand", "struct_balisong_engine_1_1_balisong_engine_renderer_1_1_draw_command.html", "struct_balisong_engine_1_1_balisong_engine_renderer_1_1_draw_command" ],
        [ "Graphics", "class_balisong_engine_1_1_balisong_engine_renderer_1_1_graphics.html", "class_balisong_engine_1_1_balisong_engine_renderer_1_1_graphics" ],
        [ "Mesh", "class_balisong_engine_1_1_balisong_engine_renderer_1_1_mesh.html", "class_balisong_engine_1_1_balisong_engine_renderer_1_1_mesh" ],
        [ "Renderer", "class_balisong_engine_1_1_balisong_engine_renderer_1_1_renderer.html", null ],
        [ "RenderParams", "struct_balisong_engine_1_1_balisong_engine_renderer_1_1_render_params.html", "struct_balisong_engine_1_1_balisong_engine_renderer_1_1_render_params" ],
        [ "Texture2D", "class_balisong_engine_1_1_balisong_engine_renderer_1_1_texture2_d.html", "class_balisong_engine_1_1_balisong_engine_renderer_1_1_texture2_d" ],
        [ "TextureConfig", "struct_balisong_engine_1_1_balisong_engine_renderer_1_1_texture_config.html", "struct_balisong_engine_1_1_balisong_engine_renderer_1_1_texture_config" ],
        [ "Vertex", "struct_balisong_engine_1_1_balisong_engine_renderer_1_1_vertex.html", "struct_balisong_engine_1_1_balisong_engine_renderer_1_1_vertex" ]
      ] ],
      [ "BalisongEngineScenes", null, [
        [ "BaseScene", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_base_scene.html", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_base_scene" ],
        [ "CreditsScene", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_credits_scene.html", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_credits_scene" ],
        [ "InputTestScene", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_input_test_scene.html", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_input_test_scene" ],
        [ "LevelScene", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_level_scene.html", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_level_scene" ],
        [ "MainMenuScene", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_main_menu_scene.html", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_main_menu_scene" ],
        [ "SceneStateMachine", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_scene_state_machine.html", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_scene_state_machine" ],
        [ "ShowcaseScene", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_showcase_scene.html", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_showcase_scene" ],
        [ "SplashScene", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_splash_scene.html", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_splash_scene" ],
        [ "TestScene", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_test_scene.html", "class_balisong_engine_1_1_balisong_engine_scenes_1_1_test_scene" ]
      ] ]
    ] ],
    [ "irrklang", "namespaceirrklang.html", [
      [ "IAudioRecorder", "classirrklang_1_1_i_audio_recorder.html", "classirrklang_1_1_i_audio_recorder" ],
      [ "IAudioStream", "classirrklang_1_1_i_audio_stream.html", "classirrklang_1_1_i_audio_stream" ],
      [ "IAudioStreamLoader", "classirrklang_1_1_i_audio_stream_loader.html", "classirrklang_1_1_i_audio_stream_loader" ],
      [ "ICapturedAudioDataReceiver", "classirrklang_1_1_i_captured_audio_data_receiver.html", "classirrklang_1_1_i_captured_audio_data_receiver" ],
      [ "IFileFactory", "classirrklang_1_1_i_file_factory.html", "classirrklang_1_1_i_file_factory" ],
      [ "IFileReader", "classirrklang_1_1_i_file_reader.html", "classirrklang_1_1_i_file_reader" ],
      [ "IRefCounted", "classirrklang_1_1_i_ref_counted.html", "classirrklang_1_1_i_ref_counted" ],
      [ "ISound", "classirrklang_1_1_i_sound.html", "classirrklang_1_1_i_sound" ],
      [ "ISoundDeviceList", "classirrklang_1_1_i_sound_device_list.html", "classirrklang_1_1_i_sound_device_list" ],
      [ "ISoundEffectControl", "classirrklang_1_1_i_sound_effect_control.html", "classirrklang_1_1_i_sound_effect_control" ],
      [ "ISoundEngine", "classirrklang_1_1_i_sound_engine.html", "classirrklang_1_1_i_sound_engine" ],
      [ "ISoundMixedOutputReceiver", "classirrklang_1_1_i_sound_mixed_output_receiver.html", "classirrklang_1_1_i_sound_mixed_output_receiver" ],
      [ "ISoundSource", "classirrklang_1_1_i_sound_source.html", "classirrklang_1_1_i_sound_source" ],
      [ "ISoundStopEventReceiver", "classirrklang_1_1_i_sound_stop_event_receiver.html", "classirrklang_1_1_i_sound_stop_event_receiver" ],
      [ "IVirtualRefCounted", "classirrklang_1_1_i_virtual_ref_counted.html", "classirrklang_1_1_i_virtual_ref_counted" ],
      [ "SAudioStreamFormat", "structirrklang_1_1_s_audio_stream_format.html", "structirrklang_1_1_s_audio_stream_format" ],
      [ "SInternalAudioInterface", "structirrklang_1_1_s_internal_audio_interface.html", "structirrklang_1_1_s_internal_audio_interface" ],
      [ "vec3d", "classirrklang_1_1vec3d.html", "classirrklang_1_1vec3d" ]
    ] ]
];